//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Result", IsNullable = false)]
  public partial class AddCaseEventResultEntity
  {

    private string caseEventIDField;

    private string caseEventStatusIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CaseEventID
    {
      get
      {
        return this.caseEventIDField;
      }
      set
      {
        this.caseEventIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CaseEventStatusID
    {
      get
      {
        return this.caseEventStatusIDField;
      }
      set
      {
        this.caseEventStatusIDField = value;
      }
    }
  }
}
