//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;
  using Tyler.Odyssey.API.Shared;

  // 
  // This source code was auto-generated by xsd, Version=4.6.1055.0.
  // 


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Message", IsNullable = false)]
  public partial class AddRelatedCaseEntity : BaseGeneratedAPIEntity
  {

    private string caseIDField;

    private string relatedCaseIDField;

    private string reasonField;

    private LOCALCONSOLIDATEREASON consolidateReasonField;

    private bool consolidateReasonFieldSpecified;

    private string commentField;

    private LOCALADDRELATEDCASE messageTypeField;

    //private string nodeIDField;

    //private string referenceNumberField;

    //private string userIDField;

    //private string sourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string CaseID
    {
      get
      {
        return this.caseIDField;
      }
      set
      {
        this.caseIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string RelatedCaseID
    {
      get
      {
        return this.relatedCaseIDField;
      }
      set
      {
        this.relatedCaseIDField = value;
      }
    }

    /// <remarks/>
    public string Reason
    {
      get
      {
        return this.reasonField;
      }
      set
      {
        this.reasonField = value;
      }
    }

    /// <remarks/>
    public LOCALCONSOLIDATEREASON ConsolidateReason
    {
      get
      {
        return this.consolidateReasonField;
      }
      set
      {
        this.consolidateReasonField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConsolidateReasonSpecified
    {
      get
      {
        return this.consolidateReasonFieldSpecified;
      }
      set
      {
        this.consolidateReasonFieldSpecified = value;
      }
    }

    /// <remarks/>
    public string Comment
    {
      get
      {
        return this.commentField;
      }
      set
      {
        this.commentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LOCALADDRELATEDCASE MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.CONSOLIDATEREASON")]
  public enum LOCALCONSOLIDATEREASON
  {

    /// <remarks/>
    Lead,

    /// <remarks/>
    Subordinate,
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.ADDRELATEDCASE")]
  public enum LOCALADDRELATEDCASE
  {

    /// <remarks/>
    AddRelatedCase,
  }

}
