//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace Tyler.Odyssey.API.JobTemplate
{
  using System.Xml.Serialization;
  using Tyler.Odyssey.API.Shared;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName = "Message", IsNullable = false)]
  public partial class FindCaseByCaseNumberEntity : BaseGeneratedAPIEntity
  {

    private string caseNumberField;

    private string[] searchNodeIDField;

    private string caseCategoryField;

    private string caseTypeField;

    private LOCALFINDCASEBYCASENUMBER messageTypeField;

    /// <remarks/>
    public string CaseNumber
    {
      get
      {
        return this.caseNumberField;
      }
      set
      {
        this.caseNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SearchNodeID", DataType = "integer")]
    public string[] SearchNodeID
    {
      get
      {
        return this.searchNodeIDField;
      }
      set
      {
        this.searchNodeIDField = value;
      }
    }

    /// <remarks/>
    public string CaseCategory
    {
      get
      {
        return this.caseCategoryField;
      }
      set
      {
        this.caseCategoryField = value;
      }
    }

    /// <remarks/>
    public string CaseType
    {
      get
      {
        return this.caseTypeField;
      }
      set
      {
        this.caseTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LOCALFINDCASEBYCASENUMBER MessageType
    {
      get
      {
        return this.messageTypeField;
      }
      set
      {
        this.messageTypeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string NodeID
    {
      get
      {
        return this.nodeIDField;
      }
      set
      {
        this.nodeIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferenceNumber
    {
      get
      {
        return this.referenceNumberField;
      }
      set
      {
        this.referenceNumberField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source
    {
      get
      {
        return this.sourceField;
      }
      set
      {
        this.sourceField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOCAL.FINDCASEBYCASENUMBER")]
  public enum LOCALFINDCASEBYCASENUMBER
  {

    /// <remarks/>
    FindCaseByCaseNumber,
  }
}
